[package]
name = "img_collector"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = "0.94.4"
clap = { version = "*", features = ["derive"] }
glob = { version = "*"}
thiserror = { version = "*" }
